name: EnderPearl
main: EnderPearl\Main
version: 1.2.2
api: [1.0.0, 1.1.0]
load: POSTWORLD
authors: [Yosshi999]
description: "EnderPearl!"

commands:
 enderpearl:
  description: "setting of EnderPearl"
  usage: "/enderpearl <key> <value>"
  permission: enderpearl.setting
permissions:
 enderpearl.*:
  description: Allows player to use all permissions
  children:
   enderpearl.setting:
    default: op
    description: Allows player to edit EnderPearl config
   enderpearl.teleport:
    default: true
    description: Allows player to teleport by using EnderPearl
